[project]
name = "demo-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10.16"
dependencies = [
    "fastapi>=0.115.13",
    "pandas>=2.2.3",
    "pydantic>=2.11.7",
    "pytest>=8.4.1",
]

[tool.pytest.ini_options]
pythonpath = ["."]
